# syntax=docker/dockerfile:1.7
FROM go-dota2-analysis-base-local AS builder

FROM alpine:3.20
RUN apk add --no-cache ca-certificates tzdata && \
    addgroup -S app && adduser -S -G app app
COPY --from=builder /out/backtester /app/backtester
USER app
WORKDIR /app
ENTRYPOINT ["/app/backtester"]
